{% set python_min = '3.10' %}
{% set name = "napari-tomotwin" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-tomotwin-{{ version }}.tar.gz
  sha256: 769eb1f7a6034cc170df36982e7ae809f828976ea812519f6c1ed82c617cb091

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - magicgui
    - matplotlib-base
    # - mrcfile  # Used in tests only
    - napari
    - napari-clusters-plotter >=0.7.2
    - numpy
    - pandas
    - python >={{ python_min }}
    - qtpy
    - scipy

test:
  imports:
    - napari_tomotwin
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-tomotwin
  summary: Several tools for the work with TomoTwin
  license: MPL-2.0
  license_file: LICENSE
  dev_url: https://github.com/MPI-Dortmund/napari-tomotwin

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - thorstenwagner
